
theme = "PaperMod"
baseurl = "https://liang0929.github.io/myblog" 
#設定主頁 url
languageCode = "zh-tw" 
#設定 Blog 語言
title = "Whatever you want" 
#設定網站標題
buildDrafts = false 
#是否產生草稿(建議選否)

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "Categories" 
url = "/categories/"
weight = 20
[[menu.main]] 
identifier = "archives" 
name = "Archives"
url = "/archives/"
weight = 30

[params.profileMode]
enabled = true
title = "Enter the Content"
subtitle = "Enter the Content"
imageUrl = "img/name.jpg"
imageWidth = 120
imageHeight = 120
imageTitle = "Enter the content"


[[params.profileMode.buttons]]
name = "Categories"
url = "/categories/"
[[params.profileMode.buttons]]
name = "Blog"
url = "/posts/"
 
[[params.profileMode.buttons]]
name = "Categories"
url = "/categories/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/liang0929"

	
[params] 
ShowBreadCrumbs = true    
#展示文章所在目錄
ShowReadingTime = true    
#展示閱讀時間
ShowShareButtons = true    
#展示分享按鈕
ShowPostNavLinks = true    
#本地其他文章連結
 
[params.cover]
linkFullImages = true    
#點擊圖片後以全螢幕檢視